name: Tagpr
on:
  push:
    branches:
    - main

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      issues: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tagpr
        id: tagpr
        uses: Songmu/tagpr@4c8e0c433614e5915a7049413885246b854dfd4e # v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Annotate major and minor tags
        if: steps.tagpr.outputs.tag != ''
        uses: ./
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
